# Generated by Django 3.1.4 on 2022-12-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodcategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='prodcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.prodcategory'),
        ),
        migrations.AddField(
            model_name='prodcategory',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Pcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.prodcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='prodcategory',
            unique_together={('slug', 'parent')},
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
